name: flex_flow_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Keep this as is

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: ^1.17.1
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: 6.1.2
  shared_preferences: 2.2.2  # Downgraded from 2.3.2
  shared_preferences_android: 2.2.0  # Downgraded from 2.3.2
  shared_preferences_foundation: 2.3.4  # Downgraded from 2.5.2
  shared_preferences_linux: 2.3.0  # Downgraded from 2.4.1
  shared_preferences_platform_interface: 2.3.1  # Downgraded from 2.4.1
  shared_preferences_web: 2.2.1  # Downgraded from 2.4.2
  shared_preferences_windows: 2.3.0  # Downgraded from 2.4.1
  sqflite: 2.2.8+4  # Downgraded from 2.3.3+1
  sqflite_common: 2.4.5+1  # Downgraded from 2.5.4+3
  timeago: 3.6.1
  url_launcher: 6.1.10  # Downgraded from 6.3.0
  url_launcher_android: 6.1.0  # Downgraded from 6.3.10
  url_launcher_ios: 6.1.0  # Downgraded from 6.3.1
  url_launcher_linux: 3.0.5  # Downgraded from 3.2.0
  url_launcher_macos: 3.0.5  # Downgraded from 3.2.1
  url_launcher_platform_interface: 2.1.5  # Downgraded from 2.3.2
  url_launcher_web: 2.0.19  # Downgraded from 2.3.3
  url_launcher_windows: 3.0.8  # Downgraded from 3.1.2
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.1.0  # Downgraded from 1.2.2
  uuid: ^4.0.0  # Kept as is
  web: 0.1.4-beta  # Added to force Flutter's version
  # Add the following to ensure compatibility
  url_launcher_windows: 3.0.8
  flutter_lints: 3.0.1  # Downgraded from 4.0.0
  lints: 3.0.0  # Downgraded from 4.0.0
  sqflite: 2.2.8+4  # Add override for sqflite
  sqflite_common: 2.4.5+1  # Add override for sqflite_common
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.0
  shared_preferences_foundation: 2.3.4
  shared_preferences_linux: 2.3.0
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  shared_preferences_windows: 2.3.0

dev_dependencies:
  flutter_lints: 3.0.1  # Downgraded from 4.0.0
  lints: 3.0.0  # Downgraded from 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
